### ISSUE TITLE
RX/TX pins and drive levels

### ISSUE THREAD

**Issue by zanppa** [kasper-73/CTC-GSi-8---Homeassistant#1]
Hi.

I'm about to implement this for my Ecoheat 400 but I was not clear on few things, and I don't want to accidentally break my unit. I wonder if you could clarify following before I start my project.

1) Is the RJ12 pinout on the end that is pushed to the CTC control unit? Or are the RJ12 cables typically wired so that the pinouts are the same on both ends?

2) You have for example RJ12 pin 6 TX and it is routed in the esphome to gpio pin 17 which is TX also. However, there is a fork for EcoHeat 400 (https://github.com/Spangsberg/CTC-EcoHeat400---Homeassistant) in which the RJ12 pin 6 goes to esphome RX. Could you confirm that RJ12 pin 6 is indeed TX (out/write from ESP) and pin 4 is RX (in/read to ESP)?

3) Can you confirm the drive levels? As the supply line is +5V I would assume the communication is also 5V signal level? However ESP microcontroller is only 3.3V as far as I know? Which voltage level should be used for the communication, 5V or 3.3V?

Thank you already in advance.

**Comment by zanppa** [comment]
Oh, one more thing...

4) Is the flow control pin (RJ12 pin 5) output from ESP or input to ESP controller? Since normally there is the RS485 transceiver block, I would assume that the CTC writes that pin to enable or disable the RS485 drivers. So it would be input to ESP?

Thanks!

**Comment by Spangsberg** [comment]
Hi

I’m the one who created the Spangsberg fork of the repository, adapting it to my own EcoHeat 412 unit.


  1.  Correct, the pinout on the RJ12 connector is the end that goet into the EcoHeat display
  2.  As I created the Spansgberg fork, those are the connections I used, and it is working.
  3.  I have my ESP32 powered only by the cable to the display unit, and both power and logic levels seems to be fine. I actually haven’t done any investigations into the logic levels on the EcoHeat.


Dennis


From: zanppa ***@***.***>
Sent: 4. oktober 2023 19:16
To: kasper-73/CTC-GSi-8---Homeassistant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kasper-73/CTC-GSi-8---Homeassistant] RX/TX pins and drive levels (Issue #1)


Hi.

I'm about to implement this for my Ecoheat 400 but I was not clear on few things, and I don't want to accidentally break my unit. I wonder if you could clarify following before I start my project.

  1.  Is the RJ12 pinout on the end that is pushed to the CTC control unit? Or are the RJ12 cables typically wired so that the pinouts are the same on both ends?
  2.  You have for example RJ12 pin 6 TX and it is routed in the esphome to gpio pin 17 which is TX also. However, there is a fork for EcoHeat 400 (https://github.com/Spangsberg/CTC-EcoHeat400---Homeassistant) in which the RJ12 pin 6 goes to esphome RX. Could you confirm that RJ12 pin 6 is indeed TX (out/write from ESP) and pin 4 is RX (in/read to ESP)?
  3.  Can you confirm the drive levels? As the supply line is +5V I would assume the communication is also 5V signal level? However ESP12 is only 3.3V as far as I know? Which voltage level should be used for the communication, 5V or 3.3V?

Thank you already in advance.

**Comment by zanppa** [comment]
Thank you for your reply.

I finally found time and courage to do the connection and got it working. I opted for an usb to isolated TTL serial adapter and a standard modbus library works fine for communication. I made some basic measurements while doing this:

- The supply voltage for Ecoheat is 5 V but the TTL serial communication is 3.3 V (all other pins but the supply)
- Standard 3.3 V TTL serial with bus idling at high (3.3 V) level
- The 0 V (GND) seems to be on chassis (earth) potential so I highly recommend isolating the communication from computer. Wifi is a good solution for the isolation
- It was enough to use only the TX and RX pins, the flow control pin(s?) need not to be used

Pinout I used and the idle voltages from Ecoheat (without cable connection or any communication ongoing) were:
| Pin number | Function | Idle voltage |
|---|---|---|
| 1 | GND | 0 V |
| 2 | +5V supply from Ecoheat | 5 V |
| 3 | No connect | 3.3 V |
| 4 | PC RX - Ecoheat TX | 3.3 V |
| 5 | No connect (flow control/write enable from Ecoheat?) | 0 V |
| 6 | PC TX - Ecoheat RX | 0 V (10 kOhm pull-down on Ecoheat) |

I did not investigate further what kind of signals there are on pins 3 or 5 as I didn't need them, so I'm not sure whether they are inputs or outputs and what their function is.

Thank you for your help, Zanppa
